from django.urls import path, URLPattern
from . import views

urlpatterns = [
    path('fetch_alldata/', views.fetch_alldata),
    path('fetch_singledata/', views.fetch_singledata),
    path('fetch_firstdata/', views.fetch_firstdata),
    path('fetch_lastdata/', views.fetch_lastdata),
    path('filter_data/', views.filter_data),
    path('exclude_data/', views.exclude_data),
    path('sort_ascending/', views.sort_ascending),
    path('sort_descending/', views.sort_descending),
    path('limiting_data/', views.limiting_data),
    path('count_data/', views.count_data),
    path('max_data/', views.max_data),
    path('min_data/', views.min_data),
    path('avg_data/', views.avg_data),
    path('sum_data/', views.sum_data),
    path('aggregate_data/', views.aggregate_data),
    path('insert_data/', views.insert_data),
    path('insert_multiple_data/', views.insert_multiple_data),
    path('delete_data/', views.delete_data),
    path('update_data/', views.update_data),
    path('equal_data/', views.equal_data),
    path('greater_then/', views.greater_then),
    path('less_then/', views.less_then),
    path('gt_equal/', views.gt_equal),
    path('lt_equal/', views.lt_equal),
    path('q_data/', views.q_data),
    path('case_sens/', views.case_sens),
    path('case_notsens/', views.case_notsens),
    path('start_with/', views.start_with),
    path('end_with/', views.end_with),
    path('data_range/', views.data_range),
    path('membership_in/', views.membership_in),
]
